add_rules("mode.debug", "mode.release")

set_toolchains("clang")
set_languages("c++23")

add_repositories("localrepo lib")

add_requires("fftw", "catch2", "eigen", "libsamplerate", "libpqxx", "websocketpp", "nlohmann_json", "hiredis", "kangaru", "librdkafka", "aws-sdk")
add_requires("libsndfile", { configs = { shared = false } })

target("main")
    set_kind("binary")
    add_files("src/*.cpp")
    add_files("src/**/*.cpp")
    add_files("include/finder/*.cppm")
    add_includedirs("include")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.std", true)
    set_policy("run.autobuild", true)
    add_packages("fftw", "libsndfile", "eigen", "libsamplerate", "libpqxx", "websocketpp", "nlohmann_json", "hiredis", "kangaru", "librdkafka", "aws-sdk")

target("domain")
    set_kind("binary")
    add_files("src/*.cpp")
    add_files("src/**/*.cpp")
    add_files("domain/*.cpp")
    add_files("domain/**/*.cpp")
    remove_files("src/main.cpp")
    add_files("include/finder/*.cppm")
    add_files("include/domain/*.cppm")
    add_includedirs("include")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.std", true)
    set_policy("run.autobuild", true)
    add_packages("fftw", "libsndfile", "eigen", "libsamplerate", "libpqxx", "websocketpp", "nlohmann_json", "hiredis", "kangaru")

target("searcher")
    set_kind("binary")
    add_files("searcher/*.cpp")
    add_files("searcher/**/*.cpp")
    add_files("src/*.cpp")
    add_files("src/**/*.cpp")
    add_files("domain/**/*.cpp")
    remove_files("src/main.cpp")
    add_files("include/finder/*.cppm")
    add_files("include/searcher/**/*.cppm")
    add_files("include/domain/**/*.cppm")
    add_files("include/thirdparty/**/*.cpp")
    add_includedirs("include")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.std", true)
    set_policy("run.autobuild", true)
    add_packages("fftw", "libsndfile", "eigen", "libsamplerate", "libpqxx", "websocketpp", "nlohmann_json", "hiredis", "kangaru", "librdkafka", "aws-sdk")

target("api")
    set_kind("binary")
    add_files("api/*.cpp")
    add_files("api/**/*.cpp")
    add_files("searcher/*.cpp")
    add_files("searcher/**/*.cpp")
    add_files("domain/**/*.cpp")
    add_files("src/*.cpp")
    add_files("src/**/*.cpp")
    remove_files("src/main.cpp")
    remove_files("searcher/main.cpp")
    add_files("include/finder/*.cppm")
    add_files("include/searcher/**/*.cppm")
    add_files("include/domain/**/*.cppm")
    add_includedirs("include")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.std", true)
    set_policy("run.autobuild", true)
    add_packages("fftw", "libsndfile", "eigen", "libsamplerate", "libpqxx", "websocketpp", "nlohmann_json", "hiredis", "kangaru")


target("websocket")
    set_kind("binary")
    add_files("websocket/*.cpp")
    add_files("websocket/**/*.cpp")
    add_files("searcher/*.cpp")
    add_files("searcher/**/*.cpp")
    add_files("domain/**/*.cpp")
    add_files("src/*.cpp")
    add_files("src/**/*.cpp")
    remove_files("src/main.cpp")
    remove_files("searcher/main.cpp")
    add_files("include/finder/*.cppm")
    add_files("include/websocket/**/*.cppm")
    add_files("include/searcher/**/*.cppm")
    add_files("include/domain/**/*.cppm")
    add_files("include/thirdparty/**/*.cpp")
    add_includedirs("include")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.std", true)
    set_policy("run.autobuild", true)
    add_packages("fftw", "libsndfile", "eigen", "libsamplerate", "libpqxx", "websocketpp", "nlohmann_json", "hiredis", "kangaru")
